packages:
  - server
  - package
catalogs:
  dev:
    '@antfu/eslint-config': ^5.1.0
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.2
    eslint: ^9.32.0
    lint-staged: ^16.1.4
    simple-git-hooks: ^2.13.1
    tinyexec: ^1.0.1
    tsx: ^4.20.3
    typescript: ^5.9.2
    unbuild: ^3.6.0
    vite: ^7.0.6
    vitest: ^3.2.4
    wait-port: ^1.1.0
    zx: ^8.8.0
  server:
    h3: ^1.15.4
    lru-cache: ^11.1.0
    nitropack: ^2.12.4
    npm-package-arg: ^13.0.0
    ofetch: ^1.4.1
    semver: ^7.7.2
    ufo: ^1.6.1
  types:
    '@types/node': ^24.2.0
    '@types/npm-package-arg': ^6.1.4
    '@types/semver': ^7.7.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
