packages:
  - server
  - package
catalogs:
  dev:
    '@antfu/eslint-config': ^4.11.0
    '@antfu/ni': ^24.3.0
    bumpp: ^10.1.0
    eslint: ^9.24.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    tinyexec: ^1.0.1
    tsx: ^4.19.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^6.2.5
    vitest: ^3.1.1
    wait-port: ^1.1.0
    zx: ^8.5.0

  server:
    h3: ^1.15.1
    lru-cache: ^11.1.0
    nitropack: ^2.11.8
    npm-package-arg: ^12.0.2
    semver: ^7.7.1
    ufo: ^1.6.1

  types:
    '@types/node': ^22.14.0
    '@types/npm-package-arg': ^6.1.4
    '@types/semver': ^7.7.0
