ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - server
  - package

catalogs:
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@antfu/ni': ^30.0.0
    bumpp: ^11.0.1
    cac: ^7.0.0
    eslint: ^10.2.0
    lint-staged: ^16.4.0
    p-retry: ^8.0.0
    simple-git-hooks: ^2.13.1
    tinyexec: ^1.1.1
    tsdown: ^0.21.7
    tsx: ^4.21.0
    typescript: ^6.0.2
    vite: ^8.0.8
    vitest: ^4.1.4
    wait-port: ^1.1.0
    zx: ^8.8.5
  server:
    h3: ^1.15.11
    lru-cache: ^11.3.3
    nitropack: ^2.13.3
    npm-package-arg: ^13.0.2
    ofetch: ^1.5.1
    semver: ^7.7.4
    ufo: ^1.6.3
  types:
    '@types/node': ^25.6.0
    '@types/npm-package-arg': ^6.1.4
    '@types/semver': ^7.7.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
