packages:
  - server
  - package
catalogs:
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@antfu/ni': ^25.0.0
    bumpp: ^10.1.1
    eslint: ^9.29.0
    lint-staged: ^16.1.1
    simple-git-hooks: ^2.13.0
    tinyexec: ^1.0.1
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^6.3.5
    vitest: ^3.2.3
    wait-port: ^1.1.0
    zx: ^8.5.5
  server:
    h3: ^1.15.3
    lru-cache: ^11.1.0
    nitropack: ^2.11.12
    npm-package-arg: ^12.0.2
    ofetch: ^1.4.1
    semver: ^7.7.2
    ufo: ^1.6.1
  types:
    '@types/node': ^24.0.1
    '@types/npm-package-arg': ^6.1.4
    '@types/semver': ^7.7.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
